# Generated by Django 4.1.7 on 2023-02-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_rename_title_pokemon_title_ru_pokemon_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='title_ru',
            new_name='title',
        ),
    ]
