# Generated by Django 4.1.7 on 2023-02-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_alter_pokemon_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='parent',
        ),
    ]
